name: ray_club_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase (base de dados)
  supabase_flutter: ^2.3.2
  supabase: ^2.0.8
  postgrest: ^2.0.0
  realtime_client: ^2.0.0
  
  # Cloudflare e Storage
  aws_signature_v4: ^0.6.4
  dio_smart_retry: ^7.0.1
  path: ^1.8.3

  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3
  flutter_hooks: ^0.20.5

  # UI e Estilo
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  qr_flutter: ^4.1.0
  smooth_page_indicator: ^1.1.0
  flutter_markdown: ^0.6.18

  # Utilitários
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  image_picker: ^1.1.2
  google_sign_in: ^6.1.6
  connectivity_plus: ^6.1.3
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  timeago: ^3.6.1

  # Navegação e Rotas
  auto_route: ^9.3.0+1
  provider: ^6.1.1

  # HTTP e Utilidades
  http: ^1.1.2
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.3

  # Segurança e Networking
  flutter_secure_storage: ^10.0.0-beta.4
  dio: ^5.4.0
  permission_handler: ^11.3.0
  device_info_plus: ^11.3.3
  flutter_local_notifications: ^19.0.0
  get_it: ^8.0.3
  share_plus: ^10.1.4
  video_player: ^2.8.3
  fl_chart: ^0.70.2

  # Persistência de Dados (Hive)
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
  # Assets e Animações
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  flutter_dotenv: ^5.1.0

  # Tracking
  app_tracking_transparency: ^2.0.4
  
  # Serialização e Models
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Deep Linking
  uni_links: ^0.5.1
  yaml: ^3.1.3
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Testes e Mocking
  bloc_test: ^10.0.0
  mockito: ^5.4.3
  mocktail: ^1.0.3

  # Qualidade do Código
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  
  # Geração de Código
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # App Icons & Splash
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.1
  flutter_gen_runner: ^5.4.0

  # Auto Route Generator
  auto_route_generator: ^9.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/workouts/
    - assets/images/categories/
    - assets/images/partners/
    - assets/images/nutrition/
    - assets/images/logos/
    - assets/images/logos/app/
    - assets/images/logos/partners/
    - assets/images/logos/brands/
    - assets/images/logos/social/
    - assets/images/logos/backgrounds/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/Century-Gothic.ttf
        - asset: assets/fonts/Century-Gothic-Bold.TTF
          weight: 700
    - family: Stinger
      fonts:
        - asset: assets/fonts/Stinger-Regular.ttf
        - asset: assets/fonts/Stinger-Bold.ttf
          weight: 700